name: Waka Readme

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

permissions:
  contents: write

jobs:
  update-readme:
    name: WakaReadme DevMetrics
    runs-on: ubuntu-latest

    steps:
      - uses: athul/waka-readme@master
        with:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}

          TARGET_PATH: README.md
          TARGET_BRANCH: main

          SECTION_NAME: waka

          TIME_RANGE: all_time
          LANG_COUNT: 5

          BLOCKS: ⣀⣄⣤⣦⣶⣷⣿

          SHOW_TIME: true
          SHOW_TOTAL: true
          SHOW_MASKED_TIME: true

          IGNORED_LANGUAGES: "Binary,YAML,JSON,TOML,SQL,Markdown"
